# Generated by Django 5.2 on 2025-05-15 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('max_teams', models.IntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64'), (128, '128'), (256, '256'), (512, '512')], verbose_name='Максимальное количество команд')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('discipline', models.CharField(choices=[('Dota 2', 'Dota 2'), ('CS 2', 'CS 2'), ('Valorant', 'Valorant'), ('LoL', 'League of Legends')], max_length=50, verbose_name='Дисциплина')),
                ('game_format', models.CharField(choices=[('1x1', '1x1'), ('2x2', '2x2'), ('3x3', '3x3'), ('5x5', '5x5')], max_length=50, verbose_name='Формат игры')),
                ('tournament_format', models.CharField(choices=[('BO1', 'BO1'), ('BO3', 'BO3'), ('BO5', 'BO5'), ('Mixed', 'Mixed (different for stages)')], max_length=50, verbose_name='Формат турнира')),
                ('location', models.CharField(choices=[('China', 'Китай'), ('Western Europe', 'Западная Европа'), ('Eastern Europe', 'Восточная Европа'), ('Southeast Asia', 'ЮВ Азия'), ('North America', 'Северная Америка'), ('South America', 'Южная Америка')], max_length=50, verbose_name='Локация')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-created_at'],
            },
        ),
    ]
