# Generated by Django 5.2 on 2025-05-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userprofile_bio_team_alter_userprofile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='team_avatars/'),
        ),
    ]
